language: node_js
node_js:
  - "8"

dist: trusty

services:
  - mongodb
  - redis-server

env:
  global:
    - NODE_ENV=ci
    - PORT=3000

cache:
  directories:
    - node_modules
    - client/node_modules

install:
  - echo "Installing dependencies..."
  - npm install
  - if [ -d client ]; then cd client && npm install && cd ..; fi
  - npm install -g wait-on

before_script:
  - echo "Building project..."
  - npm run build

script:
  - echo "Starting application..."
  - nohup npm run start > app.log 2>&1 &
  - echo "Waiting for server to be ready..."
  - wait-on http://localhost:3000
  - echo "Running tests..."
  - npm run test
