language: node_js
node_js:
  - "14"

services:
  - mongodb
  - redis-server

env:
  - NODE_ENV=ci
  - PORT=3000

cache:
  directories:
    - node_modules
    - client/node_modules

install:
  - npm install
  - npm install -g wait-on
  - npm run build

script:
  - nohup npm run start &
  - wait-on http://localhost:3000
  - npm run test
